### ISSUE TITLE
Live captureing end up with error or no output

### ISSUE THREAD

**Issue by SebBil** [PeterMosmans/tls-protocol-analyzer#6]
Hi,

i'm trying to analyse tls traffic and export all certificates out of a pcap/pcap-ng file or on live captureing. Till today i have tried it with a c/c++ programm and it worked semi good. Now i came across this repo, and i thought wow. 

Is it possible with the pypcap lib to capture live traffic and also reassemble all packet as in the pcap file analyse? I have tried some other python wrapper as pcapy and scapy but it doesn't work. i got no output or a dpkt error with NeedData exception. Do you know something about this?

Using pycharm newest version on windows and python3.7.3

Greets

UPDATE:
I got it running. Great work!!

**Comment by PeterMosmans** [comment]
Happy to hear that 😄
